server:
  port: 9999

spring:
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///db2202?serverTimezone=GMT%2B8
  redis:
    host: localhost
    port: 6379


logging:
  level:
    cn.kgc: debug
